services:
  - type: web
    name: regil-tagalogon-portfolio
    runtime: node
    repo: https://github.com/Leype83936222/regil_Tagalogon_portfolio
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
